### ISSUE TITLE
Drop direct dependency on AGP and KGP from catalog-gradle-plugin

### ISSUE THREAD

**Issue by msfjarvis** [flavioarfaria/Catalog#16]
Catalog's Gradle plugin currently includes dependencies on both the [Android and Kotlin Gradle plugins](https://github.com/flavioarfaria/Catalog/blob/a638cfcc68ac0e592b9aad6ff0023fa551db86da/catalog-gradle-plugin/build.gradle.kts#L25-L26) which forces an additional set of these rather large and unnecessary transitive dependencies being included in the dependency graphs of end users. Since Catalog generates Kotlin code for use in Android apps, it is very safe to assume that both these dependencies will already exist on the plugin classpath of users.

Lowering these from `implementation` to `compileOnly` will be a sufficient resolution for this.

## Prior art
- [slackhq/keeper-gradle-plugin](https://github.com/slackhq/keeper/blob/f39acfcf5babc5b87a4597d2eaa889c0397b6905/keeper-gradle-plugin/build.gradle.kts#L118-L121)
- [slackhq/slack-gradle-plugin](https://github.com/slackhq/slack-gradle-plugin/blob/95c8a5df9969d6f17259cd96969404e80ff40c95/slack-plugin/build.gradle.kts#L69-L94)

**Comment by flavioarfaria** [comment]
Good catch! Would you be willing to create a PR to address that? If not, I'll take a look at it when I have some free time.

**Comment by msfjarvis** [comment]
> Good catch! Would you be willing to create a PR to address that? If not, I'll take a look at it when I have some free time.

Raised #17 with the change
